# Site settings
title: Zplus Blog
SEOTitle: Zplus的博客 | Zplus Blog
header-img: img/home-bg.jpg
email: zplus@cug.edu.cn
description: "关于算法与机器学习、AKB48与乃木坂46 | 郑召作，Web & Android Lover，Infomation Security，Android Developer | 这里是 @Zplus || TYtrack 的个人博客，若有多个假设与观察一致，则选最简单的那个。"
keyword: "TYtrack, 郑召作, Zplus, 乃木坂46, 机器学习, @YuuriOreo, Zplus的博客, Zplus Blog, 博客, 个人网站, 互联网, Android, TensorFlow, 深度学习, NLP"
url: "https://tytrack.github.io/"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username:     YuuriOreo
zhihu_username:     寒武纪的笔石
github_username:    TYtrack
twitter_username:   zplus_cug
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: hux

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
# ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
# ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Entities should not be multiplied unnecessarily<br>若有多个假设与观察一致，则选最简单的那个"
sidebar-avatar: /img/avatar-hux-ny.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
         title: "TYtrack",
         href: "https://me.csdn.net/tytrack"
     },{
        title: "周明星",
        href: "https://me.csdn.net/star0116"
    },{
        title: "dukuku5038",
        href: "https://me.csdn.net/dukuku5038"
    },{
        title: "xiaowei_cqu",
        href: "https://me.csdn.net/xiaowei_cqu"
    },{
        title: "解旻的博客",
        href: "http://xieminis.me/"
    }
]
